# Nav menu
menu:
  home: /
  projects: /projects
  blog: /blog

headline: Abdelaziz Mokhnache
aboutme: PhD Student & Fullstack Javascript Developer

social:
  facebook:
    link: https://www.facebook.com/abdelazizmokhnache
    icon: icon-facebook-official
  twitter:
    link: https://www.twitter.com/abdelaziz18003
    icon: icon-twitter
  linkedIn:
    link: https://dz.linkedin.com/in/abdelaziz18003
    icon: icon-linkedin
  youtube:
    link: https://www.youtube.com/channel/UCGk9BKT15Twd5MmC32bEMBA
    icon: icon-youtube
  github:
    link: https://www.github.com/abdelaziz18003/
    icon: icon-github
  bitbucket:
    link: https://www.bitbucket.com/abdelaziz18003/
    icon: icon-bitbucket
  stackoverflow:
    link: https://stackoverflow.com/users/5192846/abdelaziz-mokhnache
    icon: icon-stackoverflow

favicon: /img/favicon.jpg


google_analytics_enabled: true
