# Nav menu
menu:
  home: /
  blog: /blog

headline: Electronic Engineer, Blogger & Web Developer

social:
  facebook: https://www.facebook.com/abdelazizmokhnache
  twitter: https://www.twitter.com/abdelaziz18003
  linkedIn: https://dz.linkedin.com/in/abdelaziz18003
  github: https://www.github.com/abdelaziz18003/
  bitbucket: https://www.bitbucket.com/abdelaziz18003/
  stackoverflow: http://stackoverflow.com/users/5192846/abdelaziz-mokhnache

favicon: /img/favicon.jpg

aboutme: |
  My name is Abdelaziz Mokhnache. I am a PHD student in digital image processing. I work as a freelance Javascript developer on Upwork mostly on Node.js/Vue.js projects. I enjoy learning new skills and sharing knowledge with others too.

google_analytics_enabled: true
